### ISSUE TITLE
Rewrite the presentation abstract

### ISSUE THREAD

**Issue by robinandeer** [guillermo-carrasco/PyConSweden2015#10]
Old abstract:

> The first part will focus of a Python genomics pipeline developed for the automated analysis of all of billions of DNA sequences, the NGI-pipeline. The focus for the second part will be on our in-house developed Flask website for delivering results to clinicians and a command line tool used to generate quality control (QC) metrics reports.

Is there a reason to submit a new text?

**Comment by guillermo-carrasco** [comment]
I think I'll try to briefly mention TACA, I really have to sit down and think about what I want to talk about :-/, I'll do it ASAP

**Comment by robinandeer** [comment]
I feel the same - I'll make time for it

I'd also ask you for some overview of NGI pipeline cause I do feel a little lost :sweat_smile:

**Comment by robinandeer** [comment]
### General:

You liked this sentence - perhaps something to use here?

> mysteries by reading the source code of life: DNA

### Part 2:
I can start like this. Probably need to boil it down some more but this is what makes sense and what I think I will have time to cover.

> We will also share how DNA sequencing is used to solve medical mysteries. Python plays a vital part in our entire process and we hope to share some best practises around web development with Flask and MongoEngine that we've picked up along the way.

**Comment by robinandeer** [comment]
Still time to send the updated abstract :sweat_smile: 

I think better late than never!

**Comment by guillermo-carrasco** [comment]
What about:

> The first part will focus on how Python manages the preprocessing and analysis of billions of DNA sequences on a completely automated way. The focus for the second part will be on our in-house developed Flask website for delivering results to clinicians and a command line tool used to generate quality control (QC) metrics reports.

Its not a huge change, but I think I'll spend the same time in `TACA` than with `ngi_pipeline`. I think as well that I can keep my part more descriptive, without entering too much (or at all) into code, and give an idea of how python is used for the whole automated thing. Some flowcharts, some mention do the tech stack of `TACA` + `ngi_pipeline`, but not code. I think that your part is more interesting to show that.

What do you think about that? You think we risk of being accused of not being technical enough, or similar?

**Comment by robinandeer** [comment]
I agree with your rewrite, just please include my updated abstract for the second part before you send it in!

> The first part will focus on how Python manages the preprocessing and analysis of billions of DNA sequences on a completely automated way. We will also cover how sequencing results are visualised using Flask and MongoEngine to solve medical mysteries in the clinic today.

I *am* still a little intimidated people would prefer something more technical. But I'm starting to think I might be able to enlighten you on some interesting code implementations from your part and vice versa. Let's talk more on Thursday!

**Comment by guillermo-carrasco** [comment]
Tack! Sent ^^
