### ISSUE TITLE
Should I mention/present TACA as well?

### ISSUE THREAD

**Issue by guillermo-carrasco** [guillermo-carrasco/PyConSweden2015#8]
TACA is entirely written in Python and it is an important part of "How Python drives the analysis of billions of DNA sequences", do you think I should dedicate a couple of minutes to it?

I would say yes, but I guess it also depends on the time slot we've got.

**Comment by robinandeer** [comment]
> the automated archiving part, I think its pretty cool, if I can say that :-P

With some "självdistans" you'd get some laughs only based on how nerdy that sentence sounds (in a good way) ^^

**Comment by robinandeer** [comment]
You already confirm this :smile:
