### ISSUE TITLE
Dividing up time: 25 min total

### ISSUE THREAD

**Issue by robinandeer** [guillermo-carrasco/PyConSweden2015#9]
How do we split the time across 25 minutes? Plan (to be updated and more detailed)
(We should probably do this in the repo at some point)

- Introduction: 5 min

- NGI pipeline: 10 min

- Scout interface: 10 min

- Conclusion: 0 min

**Comment by guillermo-carrasco** [comment]
a bit tight for the conclusion, I would say :laughing:

**Comment by robinandeer** [comment]
WIP

**Comment by guillermo-carrasco** [comment]
Do you want me to do the intro? Maybe its better since I will start talking about the downstream data management and going up to your clinical part. You can do the conclusion (if there is time :-/) Tell me if you want to do the intro, I don't mind, its just for convenience/structure :)

**Comment by robinandeer** [comment]
I want you to take the intro :+1:

**Comment by guillermo-carrasco** [comment]
Question: If am I going to start with the intro, I will say a couple of words about myself of course, I though on saying something like "and this is Robin Andeer, who works on the Clinical Genomics platform. He will say more about himself on the second part of the presentation", so that you can introduce yourself. Sounds ok?

**Comment by robinandeer** [comment]
Hehe, I was thinking the same. Generally I think we should switch as few times as possible.

I like the comparison grid ☺. Perhaps we can come back to it when we switch topic? Plan to only mention me initially

**Comment by guillermo-carrasco** [comment]
oki, I like the comparison slide as well :+1:. Let's talk about this small structural details personally at some point next week!

**Comment by robinandeer** [comment]
I'm gonna say we are about done with this - let's talk tomorrow and hopefully rehears a bit??
